using System.Runtime.CompilerServices;
using StorageMaster.Core.Interfaces;
using StorageMaster.Core.Models;

namespace StorageMaster.Core.Cleanup.Rules;

/// <summary>
/// Suggests deleting diagnostic log files generated by the Microsoft Store.
///
/// Two locations are checked:
///   1. %TEMP%\WinStore.App.*.log — per-session Store diagnostic logs.
///   2. %LOCALAPPDATA%\Packages\Microsoft.WindowsStore_*\LocalState\DiagOutputDir\
///      — persistent diagnostic output from the Store app package.
/// </summary>
public sealed class MicrosoftStoreLogsRule : ICleanupRule
{
    public string RuleId => "core.store-logs";
    public string DisplayName => "Microsoft Store Logs";
    public CleanupCategory Category => CleanupCategory.StoreLogs;

    public async IAsyncEnumerable<CleanupSuggestion> AnalyzeAsync(
        long sessionId,
        AppSettings settings,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        await Task.Yield();

        long totalBytes = 0;
        var paths = new List<string>();

        // ── Location 1: %TEMP%\WinStore.App.*.log ────────────────────────────
        var tempDir = Path.GetTempPath();
        if (Directory.Exists(tempDir))
        {
            foreach (var file in Directory.EnumerateFiles(tempDir, "WinStore.App.*.log"))
            {
                cancellationToken.ThrowIfCancellationRequested();
                try
                {
                    var info = new FileInfo(file);
                    if (!info.Exists || info.Length == 0) continue;
                    totalBytes += info.Length;
                    paths.Add(file);
                }
                catch { /* skip locked files */ }
            }
        }

        // ── Location 2: Store package DiagOutputDir ───────────────────────────
        var packagesDir = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "Packages");

        if (Directory.Exists(packagesDir))
        {
            foreach (var storePackage in Directory.EnumerateDirectories(
                         packagesDir, "Microsoft.WindowsStore_*"))
            {
                cancellationToken.ThrowIfCancellationRequested();
                var diagDir = Path.Combine(storePackage, "LocalState", "DiagOutputDir");
                if (!Directory.Exists(diagDir)) continue;
                try
                {
                    // Sizes come from the enumeration itself — the string overload
                    // would discard them and re-stat every file.
                    long dirSize = new DirectoryInfo(diagDir)
                        .EnumerateFiles("*", SearchOption.AllDirectories)
                        .Sum(file => { try { return file.Length; } catch { return 0L; } });
                    if (dirSize == 0) continue;
                    totalBytes += dirSize;
                    paths.Add(diagDir);
                }
                catch { /* skip inaccessible dirs */ }
            }
        }

        if (paths.Count == 0) yield break;

        yield return new CleanupSuggestion
        {
            Id = Guid.NewGuid(),
            RuleId = RuleId,
            Title = $"Microsoft Store logs ({paths.Count} item(s))",
            Description = $"Diagnostic log files generated by the Microsoft Store app. " +
                             $"Safe to delete — the Store recreates them as needed. " +
                             $"Estimated savings: {FormatBytes(totalBytes)}.",
            Category = Category,
            Risk = CleanupRisk.Low,
            EstimatedBytes = totalBytes,
            TargetPaths = paths,
            IsSystemPath = false,
        };
    }

    private static string FormatBytes(long b) => ByteFormat.Format(b);
}
