<Project>
  <PropertyGroup>
    <StorageMasterVersion>2.2.1</StorageMasterVersion>
    <StorageMasterAssemblyVersion>2.2.1.0</StorageMasterAssemblyVersion>
    <Version>$(StorageMasterVersion)</Version>
    <AssemblyVersion>$(StorageMasterAssemblyVersion)</AssemblyVersion>
    <FileVersion>$(StorageMasterAssemblyVersion)</FileVersion>
    <InformationalVersion>$(StorageMasterVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Company>StorageMaster</Company>
    <Product>StorageMaster</Product>
    <Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>
</Project>
